[package]
name = "qloxide"
version = "0.1.0"
edition = "2024"
authors = ["Daniel Probst <dan@probst.dev>"]
description = "Financial instrument modeling, trade management, and pricing"
license = "MIT"
repository = "https://git.sr.ht/~danprobst/qloxide"
keywords = ["finance", "quantitative", "pricing", "instruments", "trading"]
categories = ["finance"]
readme = "README.md"

[dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
jiff = { version = "0.2", features = ["serde"] }
typetag = "0.2"
