pub use rust_decimal::Decimal;

pub mod cashflows;
#[cfg(feature = "cli")]
pub mod cli;
pub mod config;
pub mod core;
pub mod curves;
pub mod dates;
#[cfg(feature = "gen")]
pub mod generator;
pub mod instruments;
pub mod market_data;
pub mod math;
pub mod portfolio;
pub mod pricing;
pub mod reference_data;
pub mod reports;
pub mod trades;
