use std::collections::HashMap;

use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

use crate::core;
use crate::dates::Date;

/// Reference to a [`SettlementIndex`] by id.
///
/// Serializes as a bare string. This is a *separate namespace* from
/// [`super::RateIndex`]: an `IndexRef` never names a rate index, and vice
/// versa (settlement indices describe how commodity settle numbers are
/// generated; rate indices describe floating-rate conventions).
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct IndexRef(pub String);

impl IndexRef {
    pub fn new(id: &str) -> IndexRef {
        IndexRef(id.to_string())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for IndexRef {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// How a settlement index generates its numbers.
///
/// The registry forms a graph (recursion is a feature): a `FrontLine`
/// selects among the contracts of a published family, an `Average` spans a
/// concrete determination period of another index, a `Spread` combines
/// weighted legs. Opacity is declared, not implied: a `Published` node is a
/// defined leaf whose constituents are outside the modeled universe (the
/// ICE Brent Index, a Platts assessment) — an id *missing* from the
/// registry is always a load error.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum IndexRule {
    /// Externally published series; the opaque leaf of every chain.
    Published { source: String },
    /// Front-month selector over a published contract family.
    FrontLine { of: IndexRef, roll: RollRule },
    /// Mean of another index over a concrete determination period.
    /// Period entries are generated by the driver at listing time —
    /// explicit dates, no calendar math in qloxide.
    Average { of: IndexRef, window: (Date, Date) },
    /// Weighted combination (diffs, cracks). ±1 until real weights are
    /// needed.
    Spread { legs: Vec<(Decimal, IndexRef)> },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum RollRule {
    RollOnExpiry,
}

/// A settlement index: instrument-independent reference data describing
/// how a published settle number is generated (design note
/// `docs/settlement-index-design-note.md`, v3).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettlementIndex {
    pub id: IndexRef,
    /// Human-readable label; falls back to the id when absent (generated
    /// period entries usually omit it).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    pub rule: IndexRule,
    /// Publication calendar NAME (no fincal dependency). Optional on
    /// period entries, whose dates are already explicit.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub calendar: Option<String>,
}

impl SettlementIndex {
    /// The display label: `display_name`, or the id itself.
    pub fn label(&self) -> &str {
        self.display_name.as_deref().unwrap_or(self.id.as_str())
    }

    /// The refs this index depends on (its outgoing graph edges).
    fn references(&self) -> Vec<&IndexRef> {
        match &self.rule {
            IndexRule::Published { .. } => Vec::new(),
            IndexRule::FrontLine { of, .. } | IndexRule::Average { of, .. } => vec![of],
            IndexRule::Spread { legs } => legs.iter().map(|(_, r)| r).collect(),
        }
    }
}

/// The settlement-index registry: every id unique, every reference
/// resolvable, no cycles. Load validation is hard — there is no
/// opaque-leaf-by-absence.
#[derive(Debug, Default)]
pub struct SettlementIndexRegistry {
    by_id: HashMap<String, SettlementIndex>,
}

impl SettlementIndexRegistry {
    /// Build a registry, erroring on duplicate ids. Call [`validate`]
    /// afterwards (split so config loading can attribute errors to files).
    ///
    /// [`validate`]: SettlementIndexRegistry::validate
    pub fn from_indices(indices: Vec<SettlementIndex>) -> core::Result<SettlementIndexRegistry> {
        let mut by_id: HashMap<String, SettlementIndex> = HashMap::new();
        for index in indices {
            let id = index.id.as_str().to_string();
            if by_id.insert(id.clone(), index).is_some() {
                return Err(core::Error::Config(format!(
                    "duplicate settlement index id '{}'",
                    id
                )));
            }
        }
        Ok(SettlementIndexRegistry { by_id })
    }

    pub fn get(&self, r: &IndexRef) -> Option<&SettlementIndex> {
        self.by_id.get(r.as_str())
    }

    pub fn is_empty(&self) -> bool {
        self.by_id.is_empty()
    }

    pub fn len(&self) -> usize {
        self.by_id.len()
    }

    /// Display label for a ref: the index's label, or — for a ref that
    /// does not resolve (only reachable pre-validation) — the raw id.
    pub fn label<'a>(&'a self, r: &'a IndexRef) -> &'a str {
        self.get(r).map(|i| i.label()).unwrap_or(r.as_str())
    }

    /// Dangling references and reference cycles are errors (one DFS pass).
    pub fn validate(&self) -> core::Result<()> {
        // Dangling refs first, so the cycle walk can trust edges resolve.
        let mut ids: Vec<&String> = self.by_id.keys().collect();
        ids.sort(); // deterministic error attribution
        for id in &ids {
            for r in self.by_id[*id].references() {
                if !self.by_id.contains_key(r.as_str()) {
                    return Err(core::Error::Config(format!(
                        "settlement index '{}' references unknown index '{}'",
                        id, r,
                    )));
                }
            }
        }

        // Cycle detection: DFS with an explicit stack, three-state marks.
        #[derive(Clone, Copy, PartialEq)]
        enum Mark {
            InProgress,
            Done,
        }
        let mut marks: HashMap<&str, Mark> = HashMap::new();
        for id in &ids {
            if marks.contains_key(id.as_str()) {
                continue;
            }
            // (node, next child to visit)
            let mut stack: Vec<(&str, Vec<&IndexRef>, usize)> = Vec::new();
            marks.insert(id.as_str(), Mark::InProgress);
            stack.push((id.as_str(), self.by_id[*id].references(), 0));
            while let Some((node, refs, next)) = stack.pop() {
                if next < refs.len() {
                    let child = refs[next].as_str();
                    stack.push((node, refs, next + 1));
                    match marks.get(child) {
                        Some(Mark::InProgress) => {
                            return Err(core::Error::Config(format!(
                                "settlement index reference cycle through '{}'",
                                child
                            )));
                        }
                        Some(Mark::Done) => {}
                        None => {
                            marks.insert(child, Mark::InProgress);
                            stack.push((child, self.by_id[child].references(), 0));
                        }
                    }
                } else {
                    marks.insert(node, Mark::Done);
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn published(id: &str) -> SettlementIndex {
        SettlementIndex {
            id: IndexRef::new(id),
            display_name: None,
            rule: IndexRule::Published {
                source: "ICE".to_string(),
            },
            calendar: Some("ICEUK".to_string()),
        }
    }

    fn front_line(id: &str, of: &str) -> SettlementIndex {
        SettlementIndex {
            id: IndexRef::new(id),
            display_name: Some("Brent 1st Line".to_string()),
            rule: IndexRule::FrontLine {
                of: IndexRef::new(of),
                roll: RollRule::RollOnExpiry,
            },
            calendar: Some("ICEUK".to_string()),
        }
    }

    fn average(id: &str, of: &str, start: Date, end: Date) -> SettlementIndex {
        SettlementIndex {
            id: IndexRef::new(id),
            display_name: None,
            rule: IndexRule::Average {
                of: IndexRef::new(of),
                window: (start, end),
            },
            calendar: None,
        }
    }

    #[test]
    fn serde_roundtrip_all_rules() {
        let indices = vec![
            published("ICE-B"),
            front_line("ICE-BRENT-1L", "ICE-B"),
            average(
                "ICE-BRENT-1L-AVG-2026-09",
                "ICE-BRENT-1L",
                Date::new(2026, 9, 1),
                Date::new(2026, 9, 30),
            ),
            SettlementIndex {
                id: IndexRef::new("NOB"),
                display_name: None,
                rule: IndexRule::Spread {
                    legs: vec![
                        (Decimal::ONE, IndexRef::new("PLATTS-NAPHTHA-1L")),
                        (-Decimal::ONE, IndexRef::new("ICE-BRENT-1L")),
                    ],
                },
                calendar: None,
            },
        ];
        let json = serde_json::to_string(&indices).unwrap();
        let back: Vec<SettlementIndex> = serde_json::from_str(&json).unwrap();
        assert_eq!(indices, back);
    }

    #[test]
    fn index_ref_serializes_as_bare_string() {
        let json = serde_json::to_string(&IndexRef::new("ICE-BRENT-INDEX")).unwrap();
        assert_eq!(json, "\"ICE-BRENT-INDEX\"");
    }

    #[test]
    fn label_falls_back_to_id() {
        let p = published("ICE-BRENT-INDEX");
        assert_eq!(p.label(), "ICE-BRENT-INDEX");
        let f = front_line("ICE-BRENT-1L", "ICE-B");
        assert_eq!(f.label(), "Brent 1st Line");
    }

    #[test]
    fn duplicate_id_errors() {
        let result = SettlementIndexRegistry::from_indices(vec![published("X"), published("X")]);
        assert!(result.unwrap_err().to_string().contains("duplicate"));
    }

    #[test]
    fn valid_graph_passes() {
        let reg = SettlementIndexRegistry::from_indices(vec![
            published("ICE-B"),
            front_line("ICE-BRENT-1L", "ICE-B"),
            average(
                "ICE-BRENT-1L-AVG-2026-09",
                "ICE-BRENT-1L",
                Date::new(2026, 9, 1),
                Date::new(2026, 9, 30),
            ),
        ])
        .unwrap();
        assert!(reg.validate().is_ok());
    }

    #[test]
    fn dangling_ref_errors() {
        let reg = SettlementIndexRegistry::from_indices(vec![front_line("ICE-BRENT-1L", "ICE-B")])
            .unwrap();
        let err = reg.validate().unwrap_err().to_string();
        assert!(err.contains("unknown index 'ICE-B'"), "{}", err);
    }

    #[test]
    fn cycle_errors() {
        let reg =
            SettlementIndexRegistry::from_indices(vec![front_line("A", "B"), front_line("B", "A")])
                .unwrap();
        let err = reg.validate().unwrap_err().to_string();
        assert!(err.contains("cycle"), "{}", err);
    }

    #[test]
    fn self_reference_is_a_cycle() {
        let reg = SettlementIndexRegistry::from_indices(vec![front_line("A", "A")]).unwrap();
        assert!(reg.validate().is_err());
    }
}
